# Generated by Django 4.2.7 on 2025-11-24 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('LIBRARIAN', 'Librarian'), ('ADMIN', 'Admin')], default='MEMBER', max_length=20)),
                ('max_loans', models.IntegerField(default=5)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code like 'can_add_book'", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Human readable name like 'Can Add Book'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows')),
                ('category', models.CharField(choices=[('BOOKS', 'Book Management'), ('LOANS', 'Loan Management'), ('USERS', 'User Management'), ('REPORTS', 'Reports & Analytics'), ('SYSTEM', 'System Settings')], default='SYSTEM', max_length=20)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='If true, new users are automatically added to this group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='groups', to='users.permission')),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='direct_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions assigned directly to this user', related_name='users_direct', to='users.permission'),
        ),
    ]
